### ISSUE TITLE
Errors when launching piPipes small RNA

### ISSUE THREAD

**Issue by iandry-rabe** [bowhan/piPipes#4]
hello, 
I have some issues when I launch piPipes small RNA analysis. 

in piPipes.stderr file, I have this lane, telling that the "variables" file is not found :
"piPipes_smallRNA.sh: line 158: piPipes-master/common/hg19/variables: Aucun fichier ou dossier de ce type".  I wanted to know where to find this file.

in piPipes.stdout file, I have : 
"[31;1m[2015-01-12 14:32:07 CET] Error: length for siRNA is not defined! please check the "variable" file under common$GENOME". Again, what is this "variable" file.

Thank you

**Comment by bowhan** [comment]
Hi,
the "variable" file is created when you run "piPipes install" INTERACTIVELY. You will be prompted to enter the values. I assume that you submit your jobs instead of running it on the command line. 
I would recommend you to run "piPipes install -g" again on command line. And piPipes will not try to run the steps that had been done previously.
Please let me know if you have other questions.
